source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EGKit_Example', :exclusive => true do
  pod 'EGKit', :path => '../'
end

target 'EGKit_Tests', :exclusive => true do
  pod 'EGKit', :path => '../'

  
end
